apiVersion: v1
kind: ConfigMap
metadata:
  name: consumesafe-config
data:
  application.properties: |
    spring.application.name=ConsumeSafe
    server.port=8080
    spring.datasource.url=jdbc:mysql://mysql:3306/consumesafe_db?createDatabaseIfNotExist=true&useSSL=false
    spring.datasource.username=root
    spring.datasource.password=rootpassword
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true