apiVersion: v1
kind: Service
metadata:
  name: consumesafe-service
spec:
  type: LoadBalancer
  selector:
    app: consumesafe
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8081
      nodePort: 30080